### ISSUE TITLE
Add pull request template to github

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-data-holder#10]
**Is your feature request related to a problem? Please describe.**
- we need a pull request template.

**Describe the solution you'd like**
- Refer other repo's in sef to create the pr template.

**Comment by Bawanthathilan** [comment]
I’ll do it

**Comment by anjula-sack** [comment]
ok :)

**Comment by jayasanka-sack** [comment]
@Bawanthathilan please mention this issue number in you pr description
