### ISSUE TITLE
Update youtube API to load 10 items per time

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-data-holder#17]
**Is your feature request related to a problem? Please describe.**
- The current script only loads 5 items per time we need at least 10 items per time.

**Describe the solution you'd like**
- Update `YoutubeAPI.java` to load 10 items per time

**Additional context**
- Regenerate a new URL and replace it with the current one

**Comment by waizuwolf** [comment]
@anjula-sack: Please review this PR.
